version: '3.8'

services:
  db:
    env_file:
      - ./.env.prod.db
    image: postgres:latest
    networks:
      - default
    ports:
      - 5432:5432
    expose: 
      - 5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

  api:
    build: 
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env.prod
    depends_on:
      - db
    networks:
      - default
    ports:
      - 8081:8000

volumes:
  postgres-data:
